image: node

stages:
  - test
  - package
  - deploy

cache:
  paths:
    - ./website/build

before_script:
  - whoami
  - pwd

test site:
  stage: test
  before_script:
    - npm install -g broken-link-checker@^0.7.8 wait-on@^2.1.0
  script:
    - cd website
    - npm install && npm run start &
    - wait-on http://localhost:3000/ --timeout 30000
    - blc --recursive --exclude-external http://localhost:3000

package site:
  stage: package
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 1h20min
    paths:
      - ./website/build/test-site

  script:
    - cd website
    - npm install
    - npm run build

deploy website:
  stage: deploy
  before_script:
    - npm install -g surge
  script:
    - surge --project ./website/build/test-site --domain testsite-aos.surge.sh
  after_script:
    - whoami
  environment:
    name: staging
    url: http://testsite-aos.surge.sh